/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ArticleDto
 */
export interface ArticleDto {
    /**
     * 
     * @type {string}
     * @memberof ArticleDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleDto
     */
    createdAt: string;
}


