/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PersonalInfo } from './personal-info';
import { Position } from './position';
import { ResultComment } from './result-comment';

/**
 * 
 * @export
 * @interface ComplaintDto
 */
export interface ComplaintDto {
    /**
     * 
     * @type {string}
     * @memberof ComplaintDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDto
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDto
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDto
     */
    address: string;
    /**
     * 
     * @type {PersonalInfo}
     * @memberof ComplaintDto
     */
    personalInfo?: PersonalInfo;
    /**
     * 
     * @type {Position}
     * @memberof ComplaintDto
     */
    position?: Position;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDto
     */
    status: string;
    /**
     * 
     * @type {ResultComment}
     * @memberof ComplaintDto
     */
    resultComment?: ResultComment;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDto
     */
    pictureUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ComplaintDto
     */
    districtId: string;
}


