/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';
import { Comment } from './comment';
import { ComplaintCode } from './complaint-code';
import { ComplaintId } from './complaint-id';
import { District } from './district';
import { PersonalInfo } from './personal-info';
import { Position } from './position';
import { ResultComment } from './result-comment';

/**
 * 
 * @export
 * @interface Complaint
 */
export interface Complaint {
    /**
     * 
     * @type {ComplaintId}
     * @memberof Complaint
     */
    id: ComplaintId;
    /**
     * 
     * @type {number}
     * @memberof Complaint
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof Complaint
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Complaint
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Complaint
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Complaint
     */
    updatedBy?: string;
    /**
     * 
     * @type {ComplaintCode}
     * @memberof Complaint
     */
    code: ComplaintCode;
    /**
     * 
     * @type {Comment}
     * @memberof Complaint
     */
    comment?: Comment;
    /**
     * 
     * @type {Address}
     * @memberof Complaint
     */
    address: Address;
    /**
     * 
     * @type {PersonalInfo}
     * @memberof Complaint
     */
    personalInfo?: PersonalInfo;
    /**
     * 
     * @type {any}
     * @memberof Complaint
     */
    picture: any;
    /**
     * 
     * @type {Position}
     * @memberof Complaint
     */
    position?: Position;
    /**
     * 
     * @type {string}
     * @memberof Complaint
     */
    status: StatusEnum;
    /**
     * 
     * @type {ResultComment}
     * @memberof Complaint
     */
    resultComment?: ResultComment;
    /**
     * 
     * @type {District}
     * @memberof Complaint
     */
    district: District;
}

/**
    * @export
    * @enum {string}
    */
export enum StatusEnum {
    Created = 'CREATED',
    InProgress = 'IN_PROGRESS',
    SentToExternalService = 'SENT_TO_EXTERNAL_SERVICE',
    Finished = 'FINISHED',
    Rejected = 'REJECTED'
}



