/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DistrictId } from './district-id';
import { DistrictName } from './district-name';
import { DistrictNameInArabic } from './district-name-in-arabic';
import { Municipality } from './municipality';

/**
 * 
 * @export
 * @interface District
 */
export interface District {
    /**
     * 
     * @type {DistrictId}
     * @memberof District
     */
    id: DistrictId;
    /**
     * 
     * @type {number}
     * @memberof District
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof District
     */
    updatedBy?: string;
    /**
     * 
     * @type {DistrictName}
     * @memberof District
     */
    name: DistrictName;
    /**
     * 
     * @type {DistrictNameInArabic}
     * @memberof District
     */
    nameInArabic: DistrictNameInArabic;
    /**
     * 
     * @type {Municipality}
     * @memberof District
     */
    municipality: Municipality;
}


