/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InformationDto
 */
export interface InformationDto {
    /**
     * 
     * @type {string}
     * @memberof InformationDto
     */
    intro: string;
    /**
     * 
     * @type {string}
     * @memberof InformationDto
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof InformationDto
     */
    email: string;
}


