/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CreateComplaintRequest } from './create-complaint-request';

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {CreateComplaintRequest}
     * @memberof InlineObject
     */
    content: CreateComplaintRequest;
    /**
     * 
     * @type {any}
     * @memberof InlineObject
     */
    file: any;
}


