/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ContentType } from './content-type';
import { FileId } from './file-id';
import { FileName } from './file-name';

/**
 * 
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * 
     * @type {FileId}
     * @memberof ModelFile
     */
    id: FileId;
    /**
     * 
     * @type {number}
     * @memberof ModelFile
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    updatedBy?: string;
    /**
     * 
     * @type {FileName}
     * @memberof ModelFile
     */
    fileName: FileName;
    /**
     * 
     * @type {ContentType}
     * @memberof ModelFile
     */
    contentType?: ContentType;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelFile
     */
    blob: Array<string>;
}


