/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ArticleWithoutContent } from './article-without-content';
import { PageNumber } from './page-number';
import { PageSize } from './page-size';

/**
 * 
 * @export
 * @interface PageArticleWithoutContent
 */
export interface PageArticleWithoutContent {
    /**
     * 
     * @type {Array<ArticleWithoutContent>}
     * @memberof PageArticleWithoutContent
     */
    elements: Array<ArticleWithoutContent>;
    /**
     * 
     * @type {PageNumber}
     * @memberof PageArticleWithoutContent
     */
    pageNumber: PageNumber;
    /**
     * 
     * @type {PageSize}
     * @memberof PageArticleWithoutContent
     */
    pageSize: PageSize;
    /**
     * 
     * @type {number}
     * @memberof PageArticleWithoutContent
     */
    totalPages: number;
}


