/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PageRegisteredUser } from './page-registered-user';
import { UserDto } from './user-dto';

/**
 * 
 * @export
 * @interface PageDtoRegisteredUserUserDto
 */
export interface PageDtoRegisteredUserUserDto {
    /**
     * 
     * @type {PageRegisteredUser}
     * @memberof PageDtoRegisteredUserUserDto
     */
    page?: PageRegisteredUser;
    /**
     * 
     * @type {object}
     * @memberof PageDtoRegisteredUserUserDto
     */
    mapper?: object;
    /**
     * 
     * @type {number}
     * @memberof PageDtoRegisteredUserUserDto
     */
    number: number;
    /**
     * 
     * @type {number}
     * @memberof PageDtoRegisteredUserUserDto
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageDtoRegisteredUserUserDto
     */
    totalPages: number;
    /**
     * 
     * @type {Array<UserDto>}
     * @memberof PageDtoRegisteredUserUserDto
     */
    elements: Array<UserDto>;
}


