/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ArticleWithoutContentDto } from './article-without-content-dto';
import { PageArticleWithoutContent } from './page-article-without-content';

/**
 * 
 * @export
 * @interface PageDtoArticleWithoutContentArticleWithoutContentDto
 */
export interface PageDtoArticleWithoutContentArticleWithoutContentDto {
    /**
     * 
     * @type {PageArticleWithoutContent}
     * @memberof PageDtoArticleWithoutContentArticleWithoutContentDto
     */
    page?: PageArticleWithoutContent;
    /**
     * 
     * @type {object}
     * @memberof PageDtoArticleWithoutContentArticleWithoutContentDto
     */
    mapper?: object;
    /**
     * 
     * @type {number}
     * @memberof PageDtoArticleWithoutContentArticleWithoutContentDto
     */
    number: number;
    /**
     * 
     * @type {number}
     * @memberof PageDtoArticleWithoutContentArticleWithoutContentDto
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageDtoArticleWithoutContentArticleWithoutContentDto
     */
    totalPages: number;
    /**
     * 
     * @type {Array<ArticleWithoutContentDto>}
     * @memberof PageDtoArticleWithoutContentArticleWithoutContentDto
     */
    elements: Array<ArticleWithoutContentDto>;
}


