/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MunicipalityDto } from './municipality-dto';
import { PageMunicipality } from './page-municipality';

/**
 * 
 * @export
 * @interface PageDtoMunicipalityMunicipalityDto
 */
export interface PageDtoMunicipalityMunicipalityDto {
    /**
     * 
     * @type {PageMunicipality}
     * @memberof PageDtoMunicipalityMunicipalityDto
     */
    page?: PageMunicipality;
    /**
     * 
     * @type {object}
     * @memberof PageDtoMunicipalityMunicipalityDto
     */
    mapper?: object;
    /**
     * 
     * @type {number}
     * @memberof PageDtoMunicipalityMunicipalityDto
     */
    number: number;
    /**
     * 
     * @type {number}
     * @memberof PageDtoMunicipalityMunicipalityDto
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof PageDtoMunicipalityMunicipalityDto
     */
    totalPages: number;
    /**
     * 
     * @type {Array<MunicipalityDto>}
     * @memberof PageDtoMunicipalityMunicipalityDto
     */
    elements: Array<MunicipalityDto>;
}


