/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonalInfoDto
 */
export interface PersonalInfoDto {
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoDto
     */
    phone?: string;
}


