/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisteredUserId
 */
export interface RegisteredUserId {
    /**
     * 
     * @type {string}
     * @memberof RegisteredUserId
     */
    rawId: string;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUserId
     */
    systemId: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUserId
     */
    anonymousId: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUserId
     */
    registeredUserId: boolean;
}


