/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CryptedPassword } from './crypted-password';
import { Email } from './email';
import { FirstName } from './first-name';
import { LastName } from './last-name';
import { RegisteredUserId } from './registered-user-id';
import { Roles } from './roles';
import { Username } from './username';

/**
 * 
 * @export
 * @interface RegisteredUser
 */
export interface RegisteredUser {
    /**
     * 
     * @type {RegisteredUserId}
     * @memberof RegisteredUser
     */
    id: RegisteredUserId;
    /**
     * 
     * @type {number}
     * @memberof RegisteredUser
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof RegisteredUser
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredUser
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredUser
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteredUser
     */
    updatedBy?: string;
    /**
     * 
     * @type {Username}
     * @memberof RegisteredUser
     */
    username: Username;
    /**
     * 
     * @type {Email}
     * @memberof RegisteredUser
     */
    email: Email;
    /**
     * 
     * @type {CryptedPassword}
     * @memberof RegisteredUser
     */
    cryptedPassword: CryptedPassword;
    /**
     * 
     * @type {FirstName}
     * @memberof RegisteredUser
     */
    firstName: FirstName;
    /**
     * 
     * @type {LastName}
     * @memberof RegisteredUser
     */
    lastName: LastName;
    /**
     * 
     * @type {Roles}
     * @memberof RegisteredUser
     */
    roles: Roles;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    registered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    system: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    municipalityResponsible: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    municipalityAuditor: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    districtResponsible: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    districtAuditor: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    anonymous: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RegisteredUser
     */
    admin: boolean;
}


