/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateInternalUserRequest
 */
export interface UpdateInternalUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateInternalUserRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInternalUserRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInternalUserRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateInternalUserRequest
     */
    lastName: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateInternalUserRequest
     */
    isAdmin: boolean;
}


