/* tslint:disable */
/* eslint-disable */
/**
 * Municipality API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    lastName: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserDto
     */
    isAdmin: boolean;
    /**
     * 
     * @type {Set<string>}
     * @memberof UserDto
     */
    municipalitiesResponsible: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof UserDto
     */
    municipalitiesAuditor: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof UserDto
     */
    districtsResponsible: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof UserDto
     */
    districtsAuditor: Set<string>;
}


