version: "3"

services:
  municipality-local-database:
    build:
      context: ../docker-context/database
      dockerfile: DockerFile
    container_name: municipality-local-database-container
    ports:
      - "6998:5432"
