const ErrorCode = {
    INTERNAL: "INTERNAL_ERROR", 
    UNAUTHORIZED: "UNAUTHORIZED", 
    MISSING_INFO: "MISSING_INFORMATION", 
    WEAK_PASSWORD: "WEAK_PASSWORD", 
    USERNAME_EXISTS: "USERNAME_EXISTS",
    EMAIL_EXISTS: "EMAIL_EXISTS", 
    INVALID_EMAIL: "INVALID_EMAIL", 
    INCORRECT_LOGIN: "INCORRECT_LOGIN_INFORMATION"
}

export default ErrorCode;